### ISSUE TITLE
Unable to  View Older Square Orders

### ISSUE THREAD

**Issue by dbltoe** [proseLA/square_webPay#17]
At least three updated sites report they are unable to see the details of Square-processed orders placed before the installation of webPay.

All order information can be obtained using Edit Orders but, clicking Details on any order made with the older Square mod throws an error stating it was trying to access square.php for the information versus square_webPay.php.

Investigation shows that the Details button uses the payment_module_code field entry in the orders table to determine what file to run in showing the details.

I first reported this in issue 16.

It appears that the quickest fix is

`UPDATE orders
SET payment_module_code = "square_webPay"
WHERE payment_module_code = "square";`

This makes all orders "show up" when clicking on Details.

You may want to handle this another way.  That's why I put it here for now rather than having folks mess up their DB.

**Comment by dbltoe** [comment]
I note that this is not a problem on sites that keep their old Square settings with usage set to false.

However, when that token expires.......

**Comment by proseLA** [comment]
hi john,
lets try and confirm some details here:

- #16 you reported 2 things.  the first thing was a db problem involving the field `language_code`.  i do not see that field at all in my repository.   after looking at that error log, the problem seemed to me mixup with some code from zc v156 and v157.  that field was added in v157 and whatever was doing the insert into the orders table was code from v157.  nothing to do with square. 
- the second issue involves some defines from the old square module.  which i do not make use of in my module.  and it seemed to me at the time that complete removal of the old module should address that.

what you are reporting now seems a bit clearer to me, and this is what i have found:

- if you remove the old square module, and click on any order that makes use of the old module, you get an error log that looks has these elements in it:
```
[14-Apr-2022 09:31:38 America/Los_Angeles] Request URI: /admin/index.php?cmd=orders&page=1&oID=104&action=edit, IP address: 192.168.14.74
#1  square->isTokenExpired() called at [/var/www/zcdev/includes/modules/payment/square.php:559]
#2  square->token_refresh_check() called at [/var/www/zcdev/includes/modules/payment/square.php:505]
#3  square->getAccessToken() called at [/var/www/zcdev/includes/modules/payment/square.php:816]
#4  square->lookupOrderDetails() called at [/var/www/zcdev/includes/modules/payment/square.php:456]
#5  square->admin_notification() called at [/var/www/zcdev/admin/orders.php:739]
#6  require(/var/www/zcdev/admin/orders.php) called at [/var/www/zcdev/admin/index.php:11]
--> PHP Warning: Use of undefined constant MODULE_PAYMENT_SQUARE_TOKEN_EXPIRES_AT - assumed 'MODULE_PAYMENT_SQUARE_TOKEN_EXPIRES_AT' (this will throw an Error in a future version of PHP) in /var/www/zcdev/includes/modules/payment/square.php on line 526.

[14-Apr-2022 09:31:38 America/Los_Angeles] PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (MODULE_PAYMENT_SQUARE_TOKEN_EXPIRES_AT) at position 0 (M): The timezone could not be found in the database in /var/www/zcdev/includes/modules/payment/square.php:526
Stack trace:
```
- if you install the old square module, and set the enable to false, i get this error:
```
[14-Apr-2022 09:20:36 America/Los_Angeles] Request URI: /admin/index.php?cmd=orders&page=1&oID=104&action=edit, IP address: 192.168.14.74
--> PHP Fatal error: Uncaught Error: Call to a member function getId() on string in /var/www/zcdev/includes/modules/payment/square.php:829
Stack trace:
#0 /var/www/zcdev/includes/modules/payment/square.php(456): square->lookupOrderDetails()
#1 /var/www/zcdev/admin/orders.php(739): square->admin_notification()
#2 /var/www/zcdev/admin/index.php(11): require('/var/www/zcdev/...')
#3 {main}
  thrown in /var/www/zcdev/includes/modules/payment/square.php on line 829.
```
is that what you are finding?

i think the admin orders script is pretty lame.

the solution that you provided with regards to updating the database is an interesting one...  although i am not sure i like it.  because now you do not know what module processed the order.

can you confirm this is what you are finding here?  

i think if an order used a payment module that is now no longer active it should not error out.

so let me investigate further.  it is possible that because i reused the `admin_notification` that could be causing the problem.

but the reality of this situation seems to be inherent in the base part of ZC.

**Comment by proseLA** [comment]
my opinion on this is to change this line:

https://github.com/zencart/zencart/blob/33cd10a3efed243071f0e5bd44b4b7835e4f46d6/admin/orders.php#L736

to:
```
if (isset($module) && (is_object($module) && method_exists($module, 'admin_notification')) && $module->enabled) {
```

**Comment by proseLA** [comment]
alternatively, one might be able to do that in that method...

i will have to think about it.  but again, the errors that you are reporting are a problem with square; and they probably will follow over to square_webPay as well.

**Comment by dbltoe** [comment]
Those are pretty much what we are getting.  I suggested the DB change as most updates will use the same/existing web application already on Square.

Essentially, the question is, does it matter if the processor was Square or which method of Square?  I'm thinking Square is Square is SquarewebPay.  All use the same transaction number and show up in Square as transactions regardless of done with the old or new.

**Comment by proseLA** [comment]
> Those are pretty much what we are getting. I suggested the DB change as most updates will use the same/existing web application already on Square.
> 
> Essentially, the question is, does it matter if the processor was Square or which method of Square? I'm thinking Square is Square is SquarewebPay. All use the same transaction number and show up in Square as transactions regardless of done with the old or new.

i'm just not sure that is a good assumption.  

some people may create a new application on their dashboard with different credentials.  so i do not know if the transaction id will work with a different app ID and secret.

in addition to which, if someone lets their OAuth token expire, the orders page will still bomb out.

and again, i think this is a problem with the square module and the zc orders script.

**Comment by dbltoe** [comment]
Finally got a chance to upgrade another site and can confirm that all is good on getting the data from the previous orders.  👍
